### PR TITLE
update to industrial_ci

### PR DESCRIPTION
**Pull request by souravran**

### CODE REVIEW

**Comment by ipa-rmb** [comment]
Hi Saurav, Travis fails is this correct?

**Comment by floweisshardt** [comment]
@ipa-rmb: travis now uses `catkin build` which is more strict than `catkin_make`. somehow libnite2 downloads something to the build directory. This should be fixed.

**Comment by ipa-rmb** [comment]
libnite downloads and unzips a library and then compiles it. If catkin build does not support downloading and self-compiling software, what would be the right approach then? So far this was fine. And it is exactly the same procedure as what is done in cob_extern - so all stuff there is also wrong?

**Comment by floweisshardt** [comment]
@ipa-rmb: you're right. most of the packages in cob_extern fail too due to the same reason: https://travis-ci.org/ipa320/cob_extern/builds/201567910

**Comment by ipa-rmb** [comment]
So what will we do with it? Is there any correct way how to do it?

**Comment by floweisshardt** [comment]
@ipa-fxm @ipa-mdl: any suggestion?

**Comment by mathias-luedtke** [comment]
The sources get mounted read-only.
All 3rd party builds needs to be done in build space as well.

Use https://cmake.org/cmake/help/v2.8.12/cmake.html#module:ExternalProject

See as well: http://answers.ros.org/question/95286/working-with-3rd-party-libraries/ ;)

**Comment by fmessmer** [comment]
replaced by #63

**Pull request closed without merging**
