### PR TITLE
OpenCV 2+3 compatibility cleanup

### PR DESCRIPTION
**Pull request by ipa-rmb**

### CODE REVIEW

**Comment by ipa-rmb** [comment]
This includes the updates from PR #72 and Travis now compiles in indigo, jade, and kinetic.

**Comment by ipa-rmb** [comment]
Functional test successful on my machine.

@pierrekilly can you please test this version and confirm that it is working.

**Comment by ipa-rmb** [comment]
@ipa-fmw , @ipa-fxm if you do not have any objections, I would merge the PR (and the now identical #72 likewise).

**Comment by pierrekilly** [comment]
I can confirm that it compiles on ROS Lunar with OpenCV 3.2.0.
I haven't started to play with it yet, so I cannot make functional tests, but I'll do it soon :)

**Comment by ipa-rmb** [comment]
Perfect, thanks for confirming.

**Review by floweisshardt — APPROVED** [review]

**Pull request merged**
