### PR TITLE
remove obsolete dependencies to cmake_modules

### PR DESCRIPTION
**Pull request by fmessmer**
found during kinetic migration

### CODE REVIEW

**Review by floweisshardt — APPROVED** [review]

**Comment by ipa-rmb** [comment]
Just for curiosity, why is cmake_modules not needed in those packages?

**Comment by fmessmer** [comment]
because `cmake_modules` is only relevant in case one of the documented packages is used (see https://github.com/ros/cmake_modules/blob/0.4-devel/README.md) ....but I found none of those packages being used...thus `cmake_modules` is an oboslete dependency...

**Comment by ipa-rmb** [comment]
Ah ok, thanks for this information. Good to know. Then I misunderstood the meaning of this cmake_modules so far.

**Comment by fmessmer** [comment]
> Ah ok, thanks for this information. Good to know. Then I misunderstood the meaning of this cmake_modules so far.

that's why it's all over the place...:wink:

**Comment by ipa-rmb** [comment]
Indeed.

**Comment by fmessmer** [comment]
@ipa-rmb ping

**Pull request merged**
